# .github/workflows/embold-scan.yml

name: Embold Code Quality Scan

# This workflow runs on every push to the 'main' branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch: 

jobs:
  embold-scan:
    # Use the latest version of Ubuntu to run the job
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out your repository code so the workflow can access it
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Download and extract the Embold scanner
      - name: Download and Extract Scanner
        run: |
          curl ${{ vars.EMBOLD_SCANNER_URL }} -o browserstack-codequality-scanner-archive.tar.gz
          tar xvf browserstack-codequality-scanner-archive.tar.gz
      # Step 3: Download the repository configuration file using a secure token
      - name: Download Repository Configuration
        run: |
          curl --silent --location --request GET "${{ vars.EMBOLD_URL_JAVA }}/api/v1/repositories/42715ca2e32bb40ac3e179419ab1c31f/scans/config/download" --header "Authorization: Bearer ${{ secrets.EMBOLD_TOKEN_JAVA }}" -o repository-configuration.json
      # Step 4: Run the Embold analysis scanner
      - name: Run Embold Scanner
        env:
          EMBOLD_TOKEN: ${{ secrets.EMBOLD_TOKEN_JAVA }}
        run: |
          ./browserstack-codequality-scanner/bin/embold-scanner analyse \
            -u ${{ vars.EMBOLD_URL_JAVA }} \
            -t $EMBOLD_TOKEN \
            -r 42715ca2e32bb40ac3e179419ab1c31f \
            -b . \
            -d ./embold-data \
            -c ./repository-configuration.json \
            -l ./embold-log \
            -sh ./embold-scanner-home
